#!/bin/sh
#

LXCLS="/usr/bin/lxc-ls"
FANCYFULL="NAME,STATE,AUTOSTART,RAM,SWAP,IPV4,IPV6"

# silently exit if there is no changelog:
if ! [ -x ${LXCLS} ] ; then
    exit 0
fi


echo
echo "============================ LXC containers ==========================="
echo "-------------------------------- ACTIVE -------------------------------"
OUTPUT="$($LXCLS --active --fancy --fancy-format $FANCYFULL)"
if [ "$(echo $OUTPUT | wc -m)" -gt 1 ] ; then
    echo "$OUTPUT"
else
    echo "<NONE>"
fi
echo "------------------------------- STOPPED -------------------------------"
OUTPUT="$($LXCLS --stopped --fancy --fancy-format NAME,STATE,AUTOSTART)"
if [ "$(echo $OUTPUT | wc -m)" -gt 1 ] ; then
    echo "$OUTPUT"
else
    echo "<NONE>"
fi
echo "-----------------------------------------------------------------------"
