#!/bin/sh
#
# An example hook script that is called after a successful
# merge is made.
#
# To enable this hook, rename this file to "post-merge".

ls -la logcheck/ignore.d.server/*-local
chmod 644 logcheck/ignore.d.server/*-local

