" -----------------------------------------------------------
" VIM - Konfiguration von Niko Ehrenfeuchter
" VIM - Version 6.3
" ~/.vimrc
" Last Change: 13. March 2007, 15:44:58
" -----------------------------------------------------------

" Settings {{{

    " Kein Vi-kompatibler Modus 
    set nocompatible

    " Alle Suchtreffer farblich hervorheben 
    set hlsearch

    " Während der Eingabe zum entsprechenden Text springen
    set incsearch

    " Groß- und Kleinschreibung bei der Suche ignorieren 
    set ignorecase

    " ignorecase abschalten, wenn Muster Großbuchstaben enthält
    set smartcase

    " Syntax-Highlighting 
    syntax on

    " Faltungsmethode = Markierungen - Standardmäßig werden {{{ zum Anfang und }}}
    " zum Ende einer Faltung verwendet
    set foldmethod=marker

    " Automatisches Einrücken
    set smartindent

    " Einrücktiefe
    set shiftwidth=4

    set tabstop=4

    " Treppeneffekt beim Copy & Paste verhindern
    set pastetoggle=<F8>

    " Backup-File anlegen
"     set backup

    " Pfad zum Backup-Verzeichnis
"    set backupdir=~/.vim/backupdir

    " Normales Verhalten der Backspace-Taste
    set backspace=2

    " Zeigt den aktuellen Modus an
    set showmode

    " Zeigt die aktuelle Cursorposition
    set ruler

    " Ein Leerzeichen nach .,?,! beim Zusammenfügen von zwei Zeilen
    set nojoinspaces

    " Statusline - 2 Zeilen hoch
    set laststatus=2

    " Modeline nur in 1. Zeile zulässig
    set modelines=1

    " Name der aktuellen Datei in Fenster-Titel-Leiste
    set title

    " Liste von Verzeichnissen die durchsucht werden
    set runtimepath=~/.vim,$VIMRUNTIME

    set viminfo='20,\"50

    set history=50

    " Pfad zum VIM-Helpfile - Diese Option ist nur nötig wenn das
    " Aufrufen der VIM-Hilfe zu einer Fehlermeldung führt
"   set helpfile=/usr/share/vim/vim63/doc/help.txt.gz       

" }}}

" Mappings {{{

    " Hervorhebungen der Suche mit Strg-L enfernen
    map <silent> <c-l> :silent nohl<cr>

" }}}

" Autocommands {{{

    if has("autocmd")

        " LastMod - Funktion beim Speichern einer Datei aufrufen
        autocmd BufWrite *.vimrc		call LastMod()
        autocmd BufWrite *.c,*.h,*.cpp	call LastMod()
        autocmd BufWrite *.tex			call LastMod()
        autocmd BufWrite *.bib			call LastMod()
        autocmd BufWrite *.gdf			call LastMod()

        " filetype plugin on

    endif

" }}}

" Funktionen {{{

    " Sucht in den ersten $tail_size Zeilen einer Datei nach dem Muster $pat
    " und erneuert das Datum wenn die Datei verändert wurde
    fun! LastMod()
		let pat = "Last Change: "
		" define nr of checked lines
		let tail_size = 20
		" get nr of overall lines
		let last_line = line("$")
		let _date = strftime("%d. %B %Y, %X")
		" before changing anything, save cursor position
		let save_cursor = getpos(".")
        if line("$") > tail_size
			" only if file is longer than $tail_size lines, check the tail too...
			let tail_start = last_line - tail_size
			exe tail_start . "," . last_line . "g/" . pat . "/s/" . pat . ".*/" . pat . "" . _date
			let last_line = tail_size
        endif
		exe "1," . last_line . "g/" . pat . "/s/" . pat . ".*/" . pat . "" . _date
		" restore cursor position
		call setpos('.', save_cursor)
    endfun

" }}}

" Syntax {{{

    " Folds
    "hi Folded ctermbg=blue ctermfg=white

    " Statusline
    "hi StatusLine cterm=bold,reverse

    if has("gui_running")
        colorscheme darkblue
    endif

" }}}

" Plugins {{{

" }}}

" Registers {{{

    " lade makro fuer cpp-debug define in register 'd'
    let @d = "O0C#ifdef DEBUGjo0C#endif"

	" TPM-kommentar in register 't'
	let @t = "A	/*TPM*/"

" }}}
