# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=5000
HISTFILESIZE=5000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

# define a function '_short_wdir' that takes the value of pwd and returns
# a truncated version (with a prefix to indicate truncation) if the length
# is above a certain limit, otherwise just $HOME is substitued by '~'
_short_wdir() {
    # how many characters of the $PWD should be kept
	local pwdmaxlen=34
    # use '~' instead of full path for homedir
	local shortPWD="${PWD/$HOME/\~}"
    # indicator that there has been directory truncation:
	local trunc_symbol="«"
	if [ ${#shortPWD} -gt $pwdmaxlen ] ; then
		local pwdoffset=$(( ${#shortPWD} - $pwdmaxlen ))
		printf "${trunc_symbol}${shortPWD:$pwdoffset:$pwdmaxlen}"
	else
		printf "${shortPWD}"
	fi
}

# define color shorthands
blw='\[\033[00m\]'     # black-white
red='\[\033[0;31m\]'   # red
grn='\[\033[0;32m\]'   # green
ylw='\[\033[0;33m\]'   # yellow
blu='\[\033[0;34m\]'   # blue
bred='\[\033[01;31m\]' # bold red
bgrn='\[\033[01;32m\]' # bold green
bylw='\[\033[01;33m\]' # bold yellow
bblu='\[\033[01;34m\]' # bold blue

# schroot struggles with TERM-settings in a screen-session, so:
if [ -n "$debian_chroot" ] && [ "$TERM" == "screen.rxvt" ] ; then
	export TERM="screen"
fi

# set a prefix if we're inside a screen since old screen-versions (or
# non-ubuntu ones) can't be easily distinguished from a regular session
[ "$TERM" == "screen" ] && scn="$bylw[S]$blw"

# red hostname if we're on SSH (doesn't work for dropbear):
if [ -n "$SSH_TTY" ] ; then
	host=$blw$red'@\h'
else
	host=$blw$bgrn'@\h'
fi
# blue directory name
wdir=$blw':'$bblu'$(_short_wdir)'$blw'\$ '

if [ "$color_prompt" = yes ]; then
	PS1=$scn$red'${debian_chroot:+($debian_chroot)}'$grn'\u'$host$wdir
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\W\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# after sourcing bash_completion, we can look for git-goodies and use them:
if type -t __git_ps1 > /dev/null ; then
    # you could insert some utf8-art like '$bred±$bgrn±$bred±' if desired
    # note: use '$ylw' instead of '$bylw' on light backgrounds
    PS1="$PS1"'$(__git_ps1 "'$bylw'(%s)'$blw' ")'
    GIT_PS1_SHOWDIRTYSTATE=yes
    GIT_PS1_SHOWSTASHSTATE=yes
    GIT_PS1_SHOWUNTRACKEDFILES=yes
fi

# clean up our variables
unset scn host wdir blw red grn ylw blu bred bgrn bylw bblu

#set bell-style none
xset b off &> /dev/null

# function definitions
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

export HOSTTYPE # required by many devel-tools
export LANG=

# give a warning if deprecated inclusion files were found:
if [ -f ~/.found_deprecated_incfiles ] ; then
    echo "WARN: Found deprecated profile include files, please migrate!"
    cat ~/.found_deprecated_incfiles | sort | uniq
fi
